### ISSUE TITLE
Laravel 5.8 rodando Oracle com driver Yajra.

### ISSUE THREAD

**Issue by jamangueira7** [jamangueira7/new-res#2]
Apos instalar a biblioteca para conexão com Oracle no Laravel, Yajra foi apresentada uma mensagem de erro: 

_"ORA-12505: TNS:listener does not currently know of SID given in connect descriptor"_

Documentação Yajra:
https://github.com/yajra/laravel-oci8

Resolução:

1 - No arquivo .env coloquei o seguinte código.

DB_CONNECTION_ORACLE=oracle
DB_HOST_ORACLE= xxx.xxx.x.x
DB_PORT_ORACLE=1521
DB_DATABASE_ORACLE=xe
DB_USERNAME_ORACLE=USER
DB_PASSWORD_ORACLE=SENHA

2 - No arquivo config/oracle.php coloquei o seguinte código:

'oracle' => [
        'driver'         => 'oracle',
        'tns'            => env('DB_TNS', ''),
        'host'           => env('DB_HOST_ORALCE', 'xxx.xxx.x.x'),
        'port'           => env('DB_PORT_ORALCE', '1521'),
        'database'       => env('DB_DATABASE_ORALCE', 'xe'),
        'username'       => env('DB_USERNAME_ORALCE', 'USER'),
        'password'       => env('DB_PASSWORD_ORALCE', 'SENHA'),
        'charset'        => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'         => env('DB_PREFIX', ''),
        'prefix_schema'  => env('DB_SCHEMA_PREFIX', ''),
        'edition'        => env('DB_EDITION', 'ora$base'),
        'server_version' => env('DB_SERVER_VERSION', '11g'),
    ],

3 - Na momento da busca fiz da seguinte maneira:

DB::connection('oracle')->table('TABELA')->get();

O segredo é colocar no database o valor do SID que é XE. 
Segue algumas issues que me ajudaram resolver o problema:

https://github.com/yajra/laravel-oci8/issues/80
https://github.com/yajra/laravel-oci8/issues/66
https://github.com/yajra/laravel-oci8/issues/75
https://github.com/yajra/laravel-oci8/issues/49
https://github.com/yajra/laravel-oci8/issues/19

**Comment by jamangueira7** [comment]
Esse erro ja foi resolvido com a solução acima.

**Comment by anasfathysalama** [comment]
=>  config\database.php  file  
 'oracle' => [
            'driver'        => 'oracle',
            'host'          => env('DB_HOST', ''),
            'port'          => env('DB_PORT', '1521'),
            'database'      => env('DB_DATABASE', ''),
            'sid' => env('DB_SID', ''),
            'username'      => env('DB_USERNAME', ''),
            'password'      => env('DB_PASSWORD', ''),
            'charset'       => env('DB_CHARSET', 'AL32UTF8'),
            'prefix'        => env('DB_PREFIX', ''),
        ],

 =>  .env file 

DB_CONNECTION=oracle
DB_HOST=host
DB_DATABASE=sid
DB_USERNAME=usernae
DB_PASSWORD=password


This Solution Work For Me
